apiVersion: v1
kind: Service
metadata:
  name: shimmy-rbac-test
  namespace: kube-scb
  labels:
    app: shimmy-rbac-test
spec:
  type: ClusterIP
  selector:
    app: shimmy-rbac-test
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
